#!/usr/bin/node

const admin = require( './admin.js' )
const session = require( './sessions.js' )

try {
  if (process.env.REQUEST_METHOD !== 'GET') throw 'GET only'

  let sess = session.newSession()

  let result = {
    jsonrpc: "2.0",
    result: {
      challenge: sess.chB64
    },
    id: 0
  }

  admin.respondHttp( 200, result )
}
catch( ex ) {
  admin.respondHttp( 500, ex.toString() )
}

