#!/usr/bin/node

const admin = require( './admin.js' )
const session = require( './sessions.js' )

try {
  if (process.env.REQUEST_METHOD !== 'GET') throw 'GET only'

  let sess = session.newSession()
  admin.respondHttp( 200, sess.chB64 )
}
catch( ex ) {
  admin.respondHttp( 500, ex.toString() )
}

