#!/usr/bin/node --jitless

// Nautilus - CABEZON Registrar Agent
// This endpoint serves Nautilus' Decentralized Identifier (DID), did:key format.

const admin = require( './admin.js' )
const { VARS } = require( './env.js' )

const DID = "did:key:zQ3shfEmjN42jTLtSJcMaJPEh7bDqPy3vRAwpArWM449trEnz"

try {
  if (process.env.REQUEST_METHOD !== 'GET') throw 'GET only'

  let did = {
    "@context": [ "https://www.w3.org/ns/did/v1.1" ],
    "id": DID,
    "verificationMethod": [
      {
        "id": DID + "#" + DID.replace(/^did:key:/u, ''),
        "type": "Multikey",
        "controller": DID,
        "publicKeyMultibase": DID.replace(/^did:key:/u, '')
      }
    ],
    "authentication": [ DID + "#" + DID.replace(/^did:key:/u, '') ],
    "assertionMethod": [ DID + "#" + DID.replace(/^did:key:/u, '') ],
    "capabilityInvocation": [ DID + "#" + DID.replace(/^did:key:/u, '') ],
    "capabilityDelegation": [ DID + "#" + DID.replace(/^did:key:/u, '') ]
  }

  console.log( "HTTP/1.1 200 OK" )
  console.log( "Content-Type: application/did+ld+json" )
  console.log( "Cache-Control: public, max-age=86400" )
  console.log( "Access-Control-Allow-Origin: *" )
  console.log( "X-Content-Type-Options: nosniff" )
  console.log( "" )
  console.log( JSON.stringify(did) )
}
catch( ex ) {
  admin.respondHttp( 500, ex.toString() )
}
