#!/usr/bin/node

const admin = require( './admin.js' )

try {
  if (process.env.REQUEST_METHOD !== 'GET') throw 'GET only'

  let did = {
    // REPLACE ON INSTALL - the following is clawface's DID as an example

    "@context": [ "https://www.w3.org/ns/did/v1.1" ],
    "id": "did:key:zQ3shoacVLjX5cgdKBjM7S9DKoPqwMjSsD2AveEX3PXKkk1ns",
    "verificationMethod": [
      {
        "id": "did:key:zQ3shoacVLjX5cgdKBjM7S9DKoPqwMjSsD2AveEX3PXKkk1ns#zQ3shoacVLjX5cgdKBjM7S9DKoPqwMjSsD2AveEX3PXKkk1ns",
      "type": "Multikey",
      "controller": "did:key:zQ3shoacVLjX5cgdKBjM7S9DKoPqwMjSsD2AveEX3PXKkk1ns",
      "publicKeyMultibase": "zQ3shoacVLjX5cgdKBjM7S9DKoPqwMjSsD2AveEX3PXKkk1ns"
      }
    ],
    "authentication": [
      "did:key:zQ3shoacVLjX5cgdKBjM7S9DKoPqwMjSsD2AveEX3PXKkk1ns#zQ3shoacVLjX5cgdKBjM7S9DKoPqwMjSsD2AveEX3PXKkk1ns"
    ],
    "assertionMethod": [
      "did:key:zQ3shoacVLjX5cgdKBjM7S9DKoPqwMjSsD2AveEX3PXKkk1ns#zQ3shoacVLjX5cgdKBjM7S9DKoPqwMjSsD2AveEX3PXKkk1ns"
    ],
    "capabilityInvocation": [
      "did:key:zQ3shoacVLjX5cgdKBjM7S9DKoPqwMjSsD2AveEX3PXKkk1ns#zQ3shoacVLjX5cgdKBjM7S9DKoPqwMjSsD2AveEX3PXKkk1ns"
    ],
    "capabilityDelegation": [
      "did:key:zQ3shoacVLjX5cgdKBjM7S9DKoPqwMjSsD2AveEX3PXKkk1ns#zQ3shoacVLjX5cgdKBjM7S9DKoPqwMjSsD2AveEX3PXKkk1ns"
    ]
  }

  console.log( "HTTP/1.1 200 OK" )
  console.log( "Content-Type: application/did+ld+json" )
  console.log( "Cache-Control: public, max-age=86400" )
  console.log( "Access-Control-Allow-Origin: *" )
  console.log( "X-Content-Type-Options: nosniff" )
  console.log( "" )
  console.log( JSON.stringify(did) )
}
catch( ex ) {
  admin.respondHttp( 500, ex.toString() )
}

