#!/usr/bin/node

const admin = require( './admin.js' )
const acl = require( './acl.js' )

async function getMenu( url ) {
  try {
    const response = await fetch( url )
    if (!response.ok) throw 'no response'

    let contents = await response.json()
    if (!contents || contents.length == 0)
      throw 'no contents'

    admin.respondHttp( 200, contents )
  }
  catch( e ) {
    admin.respondHttp( 404, e.toString() )
  }
}

if (! admin.fromWithinLAN() ) {
  admin.respondHttp( 401, "local only" )
}

if ( process.env.REQUEST_METHOD !== 'GET' ) {
  admin.respondHttp( 405, "Please use GET" )
}

let parms = admin.parseGetParams( process.env.QUERY_STRING )

if (!parms.agent)
  admin.respondHttp( 400, "missing agent pubkey param" )

let hostport = acl.pubkeyToHostPort( parms.agent )
if (!hostport) admin.respondHttp( 400, "no DID yet" )

let url = 'http://' + hostport + '/index.json';

(async () => {
  const result = await getMenu( url )
})();
