#!/usr/bin/node

// retrieve the next new contact from the queue. returns the handle
// and ec_public_key of the other agent, and unixtimestamp when they connected

const sessions = require( './sessions.js' )
const admin = require( './admin.js' )

if (! admin.fromWithinLAN() ) {
  admin.respondHttp( 401, "local only: " + process.env.REMOTE_ADDR )
}

if ( process.env.REQUEST_METHOD !== 'GET' ) {
  admin.respondHttp( 405, "Please use GET" )
}

try {
  let sess = sessions.oldestValid()

  if (!sess) {
    admin.respondHttp( 200, [] )
  }

  let result = {
    pubkey: sess.clientpubkeyhex,
    responded: sess.responded
  }

  admin.respondHttp( 200, result )
} catch( e ) {
  admin.respondHttp( 500, e.toString() )
}
