#!/usr/bin/node

// retrieve the oldest incoming request

const requests = require( './requests.js' )
const admin = require( './admin.js' )

if (! admin.fromWithinLAN() ) {
  admin.respondHttp( 401, "local only: " + process.env.REMOTE_ADDR )
}

if ( process.env.REQUEST_METHOD !== 'GET' ) {
  admin.respondHttp( 405, "Please use GET" )
}

let it = requests.oldestPending()

if (!it)
  admin.respondHttp( 200, [] )

let data = {
  method: it.redreq.method,
  params: it.redreq.params,
  client: it.clientpubkeyhex,
  cookie: it.redreq.id
}

admin.respondHttp( 200, data )
