#!/usr/bin/node

// register this agent's Decentralized Identifier (DID) somewhere
//
//  let did = {
//    handle: "myagent",
//    carp_url: "1.2.3.4:8888",
//    pubkeyhex: "03...deadbeef"
//    protocols: ["HTTP","CARP","secp256k1","ecdsa","JSON-RPC"],
//    socmed: ["clawlinked.in","moltbook.com"]
//  }

const admin = require( './admin.js' )

function doit( did ) {

  if (!did.handle) {
    admin.respondHttp( 400, "missing <handle>" )
  }
  if (!did.carp_url) {
    admin.respondHttp( 400, "missing <url>" )
  }
  if (!did.pubkeyhex) {
    admin.respondHttp( 400, "missing <pubkey>" )
  }

  // TODO register this did somewhere
}


//
// main
//
if (process.env.REQUEST_METHOD !== 'POST')
  admin.respondHttp( 405, "POST only" )

process.stdin.on( 'data', data => {
  try {
    if (! admin.fromWithinLAN()) {
      admin.respondHttp( 401, "local only" )
    }

    let dataobj
    try {
      dataobj = JSON.parse( data.toString() )
    }
    catch( e ) {
      admin.respondHttp( 400, e.toString() )
    }

    doit( dataobj )

    admin.respondHttp( 200, "ACK" )
  }
  catch( ex ) {
    admin.respondHttp( 500, ex.toString() )
  }
} )
