#!/usr/bin/node

// intent is to inform us of another agent's response to a challenge we have
// issued to them already

const session = require( './sessions.js' )
const acl = require( './acl.js' )
const adilos = require( 'adilosjs' )
const admin = require( './admin.js' )

try {
  if (process.env.REQUEST_METHOD !== 'GET') throw 'GET only'

  let rspB64, chB64, sess, pubkeyhex, aclrec

  // parse out params and validate the response

  try {
    let args = admin.parseGetParams( process.env.QUERY_STRING )

    if (!args || !args.rsp || !args.chall)
      throw 'missing arg(s), should be ?rsp=rspB64&chall=chB64'

    rspB64 = decodeURIComponent(args[0].split('=')[1] || '')
    if (!rspB64 || rspB64.length == 0) throw 'missing response parameter'

    chB64 = decodeURIComponent(args[1].split('=')[1] || '')
    if (!chB64 || chB64.length == 0) throw 'missing challenge parameter'

    sess = session.getSession( chB64 )
    if (!sess) throw 'challenge is not a valid session'

    let pubkeybytes = adilos.validateResponse( rspB64, chB64 )
    if (!pubkeybytes || pubkeybytes.length == 0)
      throw 'response is not valid for the challenge'

    pubkeyhex = adilos.toHexString( pubkeybytes )
  }
  catch( paramex ) {
    admin.respondHttp( 400, paramex.toString() )
  }

  try {
    // TODO - look up pubkey on the agent social media site and confirm the
    // caller is listed and is calling from their stated URL

    let clientip = process.env.REMOTE_ADDR
    if (!clientip) throw 'client IP address must be known'

    // compare clientip with listing IP and throw if mismatch
    // TODO
  }
  catch( listex ) {
    admin.respondHttp( 401, listex.toString() )
  }

  // Check if the caller has previously been banned by us

  try {
    aclrec = acl.getRecord( pubkeyhex )
    if ( aclrec && aclrec.bannedDate )
      throw 'banned at: ' + aclrec.bannedDate + ' for ' + aclrec.banReason
  }
  catch( bannedex ) {
    admin.respondHttp( 403, bannedex.toString() )
  }

  session.responded( chB64, pubkeyhex )

  // no previous entry and we got this far with a valid response so add to ACL
  if (!aclrec) {
    acl.newEntry( pubkeyhex )
  }

  admin.respondHttp( 200, 'Hello ' + pubkeyhex )
}
catch( ex ) {
  admin.respondHttp( 500, ex.toString() )
}
