#!/usr/bin/node

// intent is to inform us of another agent's response to a challenge we have
// issued to them already

const session = require( './sessions.js' )
const acl = require( './acl.js' )
const adilos = require( 'adilosjs' )
const admin = require( './admin.js' )

var rspB64, chB64, sess, pubkeyhex, aclrec

function validateParams( bodyobj ) {
  if (!bodyobj || !bodyobj.rsp || !bodyobj.chall)
    throw 'body should be {rsp:"<rspB64>",chall:"<chB64>"}'

  rspB64 = bodyobj.rsp
  chB64 = bodyobj.chall

  sess = session.getSession( chB64 )
  if (!sess) throw 'challenge is not a valid session'

  let pubkeybytes = adilos.validateResponse( rspB64, chB64 )
  if (!pubkeybytes || pubkeybytes.length == 0)
    throw 'invalid adilos response for challenge'

  pubkeyhex = adilos.toHexString( pubkeybytes )
}

function checkSocialMedia() {
  try {
    // TODO - look up pubkey on the agent social media site and confirm the
    // caller is listed and is calling from their stated URL

    let clientip = process.env.REMOTE_ADDR
    if (!clientip) throw 'client IP address must be known'

    // compare clientip with listing IP and throw if mismatch
    // TODO
  }
  catch( listex ) {
    admin.respondHttp( 401, listex.toString() )
  }
}

function checkBanned() {
  try {
    aclrec = acl.getRecord( pubkeyhex )
    if ( aclrec && aclrec.bannedDate )
      throw 'banned at: ' + aclrec.bannedDate + ' for ' + aclrec.banReason
  }
  catch( bannedex ) {
    admin.respondHttp( 403, bannedex.toString() )
  }
}

function handleResponse( bodystr ) {
  try {
    let bodyobj = JSON.parse( bodystr )
    validateParams( bodyobj )
  }
  catch( paramex ) {
    admin.respondHttp( 400, paramex.toString() )
  }

  checkSocialMedia()
  checkBanned()

  session.responded( chB64, pubkeyhex )

  if (!aclrec) {
    acl.newEntry( pubkeyhex )
  }
}

//
// main
//
if (process.env.REQUEST_METHOD !== 'POST')
  admin.respondHttp( 405, "POST only" )

process.stdin.on( 'data', data => {
  try {
    handleResponse( data.toString() )
    admin.respondHttp( 200, 'Hello ' + pubkeyhex )
  }
  catch( ex ) {
    admin.respondHttp( 500, ex.toString() )
  }
} )

